# Generated by Django 4.1 on 2022-08-12 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfileapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file_upload',
            name='file_name',
        ),
    ]
